### ISSUE TITLE
Ачивки

### ISSUE THREAD

**Issue by EdvardPotapenko** [EdvardPotapenko/pp_bot#2]
Добавить ачивки:

- Длина агрегата пользователя
- Кастомные условия ачивки ("Ююююху! -3") 
- Добавить соответствующие изменения в базу

**Comment by EdvardPotapenko** [comment]
Базу уже начал делать

**Comment by vova-lantsov-dev** [comment]
@EdvardPotapenko не спеши с ачивками, надо сначала составить список и продумать реализацию. У меня есть много идей, щас напишу сюда.

**Comment by vova-lantsov-dev** [comment]
Во-первых, просмотр ачивок будет через функционал inline query - выпадающий список, в котором у каждой ачивки картинка, название и описание. Нажатие на ачивку работает как кнопка "Поделиться".

Именно поэтому таблица ачивок будет состоять из 3х колонок: Название, Описание и Картинка.

**Comment by vova-lantsov-dev** [comment]
В этом формате предлагаю сразу несколько ачивок:
| Название | Описание | Картинка |
| ---------------- | ----------------- |:----------------:|
| Дрочун | Отрастить 20 см за 3 часа | - |
| Ночной пилот | Отрастить 30 см в промежутке между 3:00 и 8:00 по Киеву | - |
| Упс, это не вы потеряли? | Сократить на 50 см за 8 часов | - |

**Comment by EdvardPotapenko** [comment]
Michael Nadtochii:

Ачивка - «Азиат»: отрастите дубину в 5 см

«Сатана» - прибор длиной 666 см

«Миллениал» - достиг 100 см

**Comment by vova-lantsov-dev** [comment]
@EdvardPotapenko https://docs.google.com/spreadsheets/d/1WP6CBTvVU6JVNmhdeUMUGMLmA9KDUs89QmWnxZ0ySso/edit?usp=drivesdk переноси сюда

**Comment by vova-lantsov-dev** [comment]
Ссылка больше не активна, приглашение отправил тебе на почту. Таблица будет закрытой.

**Comment by dsim01** [comment]
@vova-lantsov-dev накинь доступ в таблицу
